name: Build and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@v5

      - name: Install latest ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo check
        run: cargo check --all --benches --bins --examples --tests --all-features

      - name: Run cargo check (without dev-dependencies to catch missing feature flags)
        if: startsWith(matrix.rust, 'nightly')
        run: cargo check -Z features=dev_dep

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run cargo test (unit tests with spooling feature)
        run: cargo test --workspace --exclude trino-integration-tests --features spooling

      - name: Run integration tests
        run: cargo test --package trino-integration-tests

  msrv:
    name: Minimum supported Rust version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Keep this in sync with `rust-version` in Cargo.toml.
      - uses: dtolnay/rust-toolchain@1.86.0
      - name: Check on the MSRV toolchain
        run: cargo check --all-features
