name: Lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Rust
      id: rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions/setup-python@v3
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
      env:
        SKIP: "no-commit-to-branch"
